Fix for the following kind of automated test failure recently observed
system.basic.WskBasicTests > Wsk Package REST should create, update, get and list a package FAILED
    org.scalatest.exceptions.TestFailedException: "0.0.[1]" was not equal to "0.0.[2]"

Add some retries to allow for entity update to settle